### ISSUE TITLE
Caption overlapping with source code in some figures

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Artificial-Intelligence#29]
In some figures, e.g. Figure 4.1 on page 79 and Figure 4.4 on page 86, the caption at the bottom overlaps with the source code.
![image](https://user-images.githubusercontent.com/7728268/103672248-5a08d780-4f7c-11eb-8d2a-2551aa66898d.png)

**Comment by karlstroetmann** [comment]
This has been fixed.  It was due to a faulty LaTeX installation in my home office.
